<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Pegawai;
use App\Models\Golongan;

class PegawaiSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'name' => 'Ir. BENNY IRAWAN ST., M.T',
                'golongan' => 'IV/a',
                'nip' => '197908192006041019',
                'asn' => 'PNS',
                'jabatan' => 'Kepala Badan',
                'tempat_lahir' => 'SUMENEP',
                'tanggal_lahir' => '1979-08-19',

                'tmt_cpns_pppk' => '2006-06-01',
                'tahun_masa_kerja_pra_pns' => 0,
                'bulan_masa_kerja_pra_pns' => 0,
                'tahun_masa_kerja_golongan_terakhir' => 18,
                'bulan_masa_kerja_golongan_terakhir' => 0,
                'tanggal_kenaikan_gaji_berkala_berikutnya' => null,

                'tmt_sk_kgb_terakhir' => null,
                'tanggal_sk_kgb_terakhir' => null,
                'nomor_sk_kgb_terakhir' => null,
                'pejabat_sk_kgb_terakhir' => null,

            ],
            [
                'name' => 'ABDUL KAHIR SE, M.Si',
                'golongan' => 'IV/b',
                'nip' => '196803261994031008',
                'asn' => 'PNS',
                'jabatan' => 'Sekretaris Badan',
                'tempat_lahir' => 'SUMENEP',
                'tanggal_lahir' => '1968-03-26',

                'tmt_cpns_pppk' => null,
                'tahun_masa_kerja_pra_pns' => null,
                'bulan_masa_kerja_pra_pns' => null,
                'tahun_masa_kerja_golongan_terakhir' => null,
                'bulan_masa_kerja_golongan_terakhir' => null,
                'tanggal_kenaikan_gaji_berkala_berikutnya' => null,

                'tmt_sk_kgb_terakhir' => null,
                'tanggal_sk_kgb_terakhir' => null,
                'nomor_sk_kgb_terakhir' => null,
                'pejabat_sk_kgb_terakhir' => null,
            ],
            [
                'name' => 'RACHMAT RACHMAN S.A.N., M.A.P.',
                'golongan' => 'III/c',
                'nip' => '198412302010011001',
                'asn' => 'PNS',
                'jabatan' => 'Kepala Sub Bagian',
                'tempat_lahir' => 'PROBOLINGGO',
                'tanggal_lahir' => '1984-12-30',

                'tmt_cpns_pppk' => null,
                'tahun_masa_kerja_pra_pns' => null,
                'bulan_masa_kerja_pra_pns' => null,
                'tahun_masa_kerja_golongan_terakhir' => null,
                'bulan_masa_kerja_golongan_terakhir' => null,
                'tanggal_kenaikan_gaji_berkala_berikutnya' => null,

                'tmt_sk_kgb_terakhir' => null,
                'tanggal_sk_kgb_terakhir' => null,
                'nomor_sk_kgb_terakhir' => null,
                'pejabat_sk_kgb_terakhir' => null,
            ],
            [
                'name' => 'MOH. ARIS',
                'golongan' => 'V',
                'nip' => '198604082025211001',
                'asn' => 'PPPK',
                'jabatan' => 'PENGADMINISTRASI PERKANTORAN',
                'tempat_lahir' => 'SUMENEP',
                'tanggal_lahir' => '1986-04-08',

                'tmt_cpns_pppk' => null,
                'tahun_masa_kerja_pra_pns' => null,
                'bulan_masa_kerja_pra_pns' => null,
                'tahun_masa_kerja_golongan_terakhir' => null,
                'bulan_masa_kerja_golongan_terakhir' => null,
                'tanggal_kenaikan_gaji_berkala_berikutnya' => null,

                'tmt_sk_kgb_terakhir' => null,
                'tanggal_sk_kgb_terakhir' => null,
                'nomor_sk_kgb_terakhir' => null,
                'pejabat_sk_kgb_terakhir' => null,
            ],
            [
                'name' => 'IDA OKVINITA SH',
                'golongan' => 'IX',
                'nip' => '198210112025212001',
                'asn' => 'PPPK',
                'jabatan' => 'PENATA LAYANAN OPERASIONAL',
                'tempat_lahir' => 'SUMENEP',
                'tanggal_lahir' => '1982-10-11',

                'tmt_cpns_pppk' => null,
                'tahun_masa_kerja_pra_pns' => null,
                'bulan_masa_kerja_pra_pns' => null,
                'tahun_masa_kerja_golongan_terakhir' => null,
                'bulan_masa_kerja_golongan_terakhir' => null,
                'tanggal_kenaikan_gaji_berkala_berikutnya' => null,

                'tmt_sk_kgb_terakhir' => null,
                'tanggal_sk_kgb_terakhir' => null,
                'nomor_sk_kgb_terakhir' => null,
                'pejabat_sk_kgb_terakhir' => null,
            ],
            [
                'name' => 'ANITA RACHMASARI S.Sos',
                'golongan' => 'IX',
                'nip' => '198704192025212001',
                'asn' => 'PPPK',
                'jabatan' => 'PENATA LAYANAN OPERASIONAL',
                'tempat_lahir' => 'DENPASAR',
                'tanggal_lahir' => '1987-04-19',

                'tmt_cpns_pppk' => null,
                'tahun_masa_kerja_pra_pns' => null,
                'bulan_masa_kerja_pra_pns' => null,
                'tahun_masa_kerja_golongan_terakhir' => null,
                'bulan_masa_kerja_golongan_terakhir' => null,
                'tanggal_kenaikan_gaji_berkala_berikutnya' => null,

                'tmt_sk_kgb_terakhir' => null,
                'tanggal_sk_kgb_terakhir' => null,
                'nomor_sk_kgb_terakhir' => null,
                'pejabat_sk_kgb_terakhir' => null,
            ],
            [
                'name' => 'ANDY CHANDRA KUSUMA ST',
                'golongan' => 'III/d',
                'nip' => '197105212006041014',
                'asn' => 'PNS',
                'jabatan' => 'Perencana Ahli Muda',
                'tempat_lahir' => 'SUMENEP',
                'tanggal_lahir' => '1971-05-21',

                'tmt_cpns_pppk' => null,
                'tahun_masa_kerja_pra_pns' => null,
                'bulan_masa_kerja_pra_pns' => null,
                'tahun_masa_kerja_golongan_terakhir' => null,
                'bulan_masa_kerja_golongan_terakhir' => null,
                'tanggal_kenaikan_gaji_berkala_berikutnya' => null,

                'tmt_sk_kgb_terakhir' => null,
                'tanggal_sk_kgb_terakhir' => null,
                'nomor_sk_kgb_terakhir' => null,
                'pejabat_sk_kgb_terakhir' => null,
            ],
            [
                'name' => 'ABDUR RASYID S.Sos., M.A.P.',
                'golongan' => 'IV/a',
                'nip' => '197311212006041006',
                'asn' => 'PNS',
                'jabatan' => 'Perencana Ahli Muda',
                'tempat_lahir' => 'SUMENEP',
                'tanggal_lahir' => '1973-11-21',

                'tmt_cpns_pppk' => '2006-04-01',
                'tahun_masa_kerja_pra_pns' => null,
                'bulan_masa_kerja_pra_pns' => null,
                'tahun_masa_kerja_golongan_terakhir' => 24,
                'bulan_masa_kerja_golongan_terakhir' => 0,
                'tanggal_kenaikan_gaji_berkala_berikutnya' => null,

                'tmt_sk_kgb_terakhir' => null,
                'tanggal_sk_kgb_terakhir' => null,
                'nomor_sk_kgb_terakhir' => null,
                'pejabat_sk_kgb_terakhir' => null,
            ],
            [
                'name' => 'PYEPIT RINEKSO ANDRIYANTO M.Kom.',
                'golongan' => 'III/b',
                'nip' => '199102252025041002',
                'asn' => 'PNS',
                'jabatan' => 'Perekayasa Ahli Pertama',
                'tempat_lahir' => 'SUMENEP',
                'tanggal_lahir' => '1991-02-25',

                'tmt_cpns_pppk' => null,
                'tahun_masa_kerja_pra_pns' => null,
                'bulan_masa_kerja_pra_pns' => null,
                'tahun_masa_kerja_golongan_terakhir' => null,
                'bulan_masa_kerja_golongan_terakhir' => null,
                'tanggal_kenaikan_gaji_berkala_berikutnya' => null,

                'tmt_sk_kgb_terakhir' => null,
                'tanggal_sk_kgb_terakhir' => null,
                'nomor_sk_kgb_terakhir' => null,
                'pejabat_sk_kgb_terakhir' => null,
            ],
            [
                'name' => 'MOHAMMAD ALFIN WIDYANTO M.Han',
                'golongan' => 'III/b',
                'nip' => '199510082025041003',
                'asn' => 'PNS',
                'jabatan' => 'Peneliti Ahli Pertama',
                'tempat_lahir' => 'BANDUNG',
                'tanggal_lahir' => '1995-10-08',

                'tmt_cpns_pppk' => null,
                'tahun_masa_kerja_pra_pns' => null,
                'bulan_masa_kerja_pra_pns' => null,
                'tahun_masa_kerja_golongan_terakhir' => null,
                'bulan_masa_kerja_golongan_terakhir' => null,
                'tanggal_kenaikan_gaji_berkala_berikutnya' => null,

                'tmt_sk_kgb_terakhir' => null,
                'tanggal_sk_kgb_terakhir' => null,
                'nomor_sk_kgb_terakhir' => null,
                'pejabat_sk_kgb_terakhir' => null,
            ],
            [
                'name' => 'ABDUL GANI S.A.N',
                'golongan' => 'III/b',
                'nip' => '198301192010011001',
                'asn' => 'PNS',
                'jabatan' => 'Analis Penelitian dan Pengembangan',
                'tempat_lahir' => 'SUMENEP',
                'tanggal_lahir' => '1983-01-19',

                'tmt_cpns_pppk' => null,
                'tahun_masa_kerja_pra_pns' => null,
                'bulan_masa_kerja_pra_pns' => null,
                'tahun_masa_kerja_golongan_terakhir' => null,
                'bulan_masa_kerja_golongan_terakhir' => null,
                'tanggal_kenaikan_gaji_berkala_berikutnya' => null,

                'tmt_sk_kgb_terakhir' => null,
                'tanggal_sk_kgb_terakhir' => null,
                'nomor_sk_kgb_terakhir' => null,
                'pejabat_sk_kgb_terakhir' => null,
            ],
            [
                'name' => 'MEILANY EKAWATI SE',
                'golongan' => 'III/d',
                'nip' => '197905082008012021',
                'asn' => 'PNS',
                'jabatan' => 'Penyusun Penelitian Dan Pengembangan',
                'tempat_lahir' => 'SUMENEP',
                'tanggal_lahir' => '1979-05-08',

                'tmt_cpns_pppk' => null,
                'tahun_masa_kerja_pra_pns' => null,
                'bulan_masa_kerja_pra_pns' => null,
                'tahun_masa_kerja_golongan_terakhir' => null,
                'bulan_masa_kerja_golongan_terakhir' => null,
                'tanggal_kenaikan_gaji_berkala_berikutnya' => null,

                'tmt_sk_kgb_terakhir' => null,
                'tanggal_sk_kgb_terakhir' => null,
                'nomor_sk_kgb_terakhir' => null,
                'pejabat_sk_kgb_terakhir' => null,
            ],
            [
                'name' => 'HIKMATUL AMALIYAH ST',
                'golongan' => 'III/c',
                'nip' => '198205292008012007',
                'asn' => 'PNS',
                'jabatan' => 'ANALIS BARANG MILIK NEGARA',
                'tempat_lahir' => 'SUMENEP',
                'tanggal_lahir' => '1982-05-29',

                'tmt_cpns_pppk' => null,
                'tahun_masa_kerja_pra_pns' => null,
                'bulan_masa_kerja_pra_pns' => null,
                'tahun_masa_kerja_golongan_terakhir' => null,
                'bulan_masa_kerja_golongan_terakhir' => null,
                'tanggal_kenaikan_gaji_berkala_berikutnya' => null,

                'tmt_sk_kgb_terakhir' => null,
                'tanggal_sk_kgb_terakhir' => null,
                'nomor_sk_kgb_terakhir' => null,
                'pejabat_sk_kgb_terakhir' => null,
            ],
            [
                'name' => 'FATIMAH SALEH SE., M.A.P.',
                'golongan' => 'III/b',
                'nip' => '198207312010012002',
                'asn' => 'PNS',
                'jabatan' => 'Analis Penelitian dan Pengembangan',
                'tempat_lahir' => 'SUMENEP',
                'tanggal_lahir' => '1982-07-31',

                'tmt_cpns_pppk' => null,
                'tahun_masa_kerja_pra_pns' => null,
                'bulan_masa_kerja_pra_pns' => null,
                'tahun_masa_kerja_golongan_terakhir' => null,
                'bulan_masa_kerja_golongan_terakhir' => null,
                'tanggal_kenaikan_gaji_berkala_berikutnya' => null,

                'tmt_sk_kgb_terakhir' => null,
                'tanggal_sk_kgb_terakhir' => null,
                'nomor_sk_kgb_terakhir' => null,
                'pejabat_sk_kgb_terakhir' => null,
            ],
            [
                'name' => 'SITI MUNAWAROH ST',
                'golongan' => 'III/d',
                'nip' => '197305152006042023',
                'asn' => 'PNS',
                'jabatan' => 'Analis Penelitian dan Pengembangan',
                'tempat_lahir' => 'SUMENEP',
                'tanggal_lahir' => '1973-05-15',

                'tmt_cpns_pppk' => null,
                'tahun_masa_kerja_pra_pns' => null,
                'bulan_masa_kerja_pra_pns' => null,
                'tahun_masa_kerja_golongan_terakhir' => null,
                'bulan_masa_kerja_golongan_terakhir' => null,
                'tanggal_kenaikan_gaji_berkala_berikutnya' => null,

                'tmt_sk_kgb_terakhir' => null,
                'tanggal_sk_kgb_terakhir' => null,
                'nomor_sk_kgb_terakhir' => null,
                'pejabat_sk_kgb_terakhir' => null,
            ],
            [
                'name' => 'VEBRIANI RETNOSARI A.Md.Keb',
                'golongan' => 'II/d',
                'nip' => '198602212017042005',
                'asn' => 'PNS',
                'jabatan' => 'Pengelola Kepegawaian',
                'tempat_lahir' => 'SUMENEP',
                'tanggal_lahir' => '1986-02-21',

                'tmt_cpns_pppk' => null,
                'tahun_masa_kerja_pra_pns' => null,
                'bulan_masa_kerja_pra_pns' => null,
                'tahun_masa_kerja_golongan_terakhir' => null,
                'bulan_masa_kerja_golongan_terakhir' => null,
                'tanggal_kenaikan_gaji_berkala_berikutnya' => null,

                'tmt_sk_kgb_terakhir' => null,
                'tanggal_sk_kgb_terakhir' => null,
                'nomor_sk_kgb_terakhir' => null,
                'pejabat_sk_kgb_terakhir' => null,
            ],
            [
                'name' => 'NUSURI',
                'golongan' => 'III/a',
                'nip' => '196711032007011011',
                'asn' => 'PNS',
                'jabatan' => 'Pengadministrasi Perencanaan dan Program',
                'tempat_lahir' => 'SUMENEP',
                'tanggal_lahir' => '1967-11-03',

                'tmt_cpns_pppk' => null,
                'tahun_masa_kerja_pra_pns' => null,
                'bulan_masa_kerja_pra_pns' => null,
                'tahun_masa_kerja_golongan_terakhir' => null,
                'bulan_masa_kerja_golongan_terakhir' => null,
                'tanggal_kenaikan_gaji_berkala_berikutnya' => null,

                'tmt_sk_kgb_terakhir' => null,
                'tanggal_sk_kgb_terakhir' => null,
                'nomor_sk_kgb_terakhir' => null,
                'pejabat_sk_kgb_terakhir' => null,
            ],
            [
                'name' => 'MASRAWI',
                'golongan' => 'II/d',
                'nip' => '197207212007011013',
                'asn' => 'PNS',
                'jabatan' => 'Pengadministrasi Umum',
                'tempat_lahir' => 'SUMENEP',
                'tanggal_lahir' => '1972-07-21',

                'tmt_cpns_pppk' => null,
                'tahun_masa_kerja_pra_pns' => null,
                'bulan_masa_kerja_pra_pns' => null,
                'tahun_masa_kerja_golongan_terakhir' => null,
                'bulan_masa_kerja_golongan_terakhir' => null,
                'tanggal_kenaikan_gaji_berkala_berikutnya' => null,

                'tmt_sk_kgb_terakhir' => null,
                'tanggal_sk_kgb_terakhir' => null,
                'nomor_sk_kgb_terakhir' => null,
                'pejabat_sk_kgb_terakhir' => null,
            ],
        ];

        foreach ($data as $pegawai) {
            $userId = User::where('name', $pegawai['name'])->value('id');
            $golonganId = Golongan::where('golongan', $pegawai['golongan'])->value('id');

            Pegawai::create([
                'user_id' => $userId,
                'golongan_id' => $golonganId,
                'nip' => $pegawai['nip'],
                'asn' => strtoupper($pegawai['asn']),
                'jabatan' => $pegawai['jabatan'],
                'tempat_lahir' => $pegawai['tempat_lahir'],
                'tanggal_lahir' => $pegawai['tanggal_lahir'],
                'tmt_cpns_pppk' => null,
                'tahun_masa_kerja_pra_pns' => null,
                'bulan_masa_kerja_pra_pns' => null,
                'tahun_masa_kerja_golongan_terakhir' => null,
                'bulan_masa_kerja_golongan_terakhir' => null,
                'tanggal_kenaikan_gaji_berkala_berikutnya' => null,
                'tmt_sk_kgb_terakhir' => null,
                'tanggal_sk_kgb_terakhir' => null,
                'nomor_sk_kgb_terakhir' => null,
                'pejabat_sk_kgb_terakhir' => null,
            ]);
        }
    }
}
